default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picsbook_development

test:
  <<: *default
  database: picsbook_test

production:
  <<: *default
  database: picsbook_production
  username: picsbook
  password: <%= ENV['PICSBOOK_DATABASE_PASSWORD'] %>
